title: Raj Nath Sah
description: Data engineer equipped with SQL, PL/SQL, Python, Shell scripting and Automation
permalink: ':title/'
baseurl: "/rajnathsah.github.io"
url: "rajnathsah.github.io/"
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Raj Nath Sah
author-img: myimg.jpg
about-author: Developer with interest in Python, Sql, Pl/Sql, Big Data, Data analytics and DATA. # add description
social-twitter: raj_nath_sah
social-facebook: raj4u4all
social-github: rajnathsah
social-linkedin: rajnathsah
social-email: rajnath@live.in

# Disqus
discus-identifier: https-rajnathsah-github-io

# Tracker
analytics: http://bit.ly/34cRtiO

# Build Settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
